#!/bin/bash

was_playing=0

d_artist() {
    mpc list artist | sort -f | dmenu -p artist "${dmenu_args[@]}"
}

d_album() {
    local artist="$1"
    {
        echo "[ALL]"
        mpc list album artist "$artist" | sort -f
    } | dmenu -p album "${dmenu_args[@]}"
}

d_playlist() {
    mpc playlist -f '%position% - %title% - %album% - %artist%' | dmenu -p track "${dmenu_args[@]}"
}

is_playing() {
    [[ "$(mpc current)" ]]
}

mode=library
pivoted=0
our_args=()
dmenu_args=()

for arg do
    if [[ "$arg" == "::" ]]; then
        pivoted=1
        continue
    fi

    if (( pivoted )); then
        dmenu_args+=( "$arg" )
    else
        case "$arg" in
            -l) mode=library ;;
            -p) mode=playlist ;;
        esac
    fi
done

case "$mode" in
    library)
        artist="$(d_artist)"
        [[ "$artist" ]] || exit 1

        album="$(d_album "$artist")"
        [[ "$album" ]] || exit 2

        if is_playing; then
            was_playing=1
        fi

        mpc clear
        if [[ "$album" == "[ALL]" ]]; then
            mpc find artist "$artist" | mpc add
        else
            mpc find artist "$artist" album "$album" | mpc add
        fi

        if (( was_playing )); then
            mpc play >/dev/null 2>&1
        fi
    ;;
    playlist)
        mpc play "$(d_playlist)"
    ;;
esac

